travis:
  secure:
    BINSTAR_TOKEN: GMhvHqqM6+YlW955t2HUNkp1+mvxigw/ObVRbrQX6iB959YqMn56P9jK2wtEjrw5xWPrIZfhyBMFo8AftsnYhFrDfePR+NXvclJMM4EIysFKsEF6iAnGvZo/3uFrNBDkvXiJ56PNvsA+WaT09BG8QZkmjGuyWPlFmJu5A9eb0yzXu9PryTlvmu14D+H+96ZyjZJ83Tc4MLrrWriLmmTaH9Jr7F79XtGd0VwYTof4zyWnwge0YP69h8jXrfU2J68IOWeXT7q577t81VDzNsBB9lBlIqiWn2XRX3c3kFK8Axlg1lcNcOdrTkHuSCcknw3SmF6n1Q6TWr8B+2E7x9KNfA4/AnU5Rrxwk7btghk5knk0xAP/mya7EVrmBGj1L0B1BGzVHPE7SgpsXDOMqmpavdDKK10ygoC78wloOrP23/2fqtufiM7YhGxatsfYGvP2tripQ3BCWz2Mq+tcNXy7ZQS1Nu/ToJGlGNq/GpNHmC+U2e04VCKNOAuJtG6RD3nzT3XisHwuV6hsLDLNrJsOolyxbTOduihKizMdjKigiiMFOm0ee8Bn0Iho4mK60yNVQrrLAePHjI6sbrrbcXLya4OXDPuVF9WKZPrejCsOU/TDDf+EXKK3m1PmKkM8bQh7EaXfFfMf02igUFZh3l3rKIvQGMO21td3UrhQWYyvWEg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
